spring:
  boot:
    admin:
      url: http://localhost:8083

server:
  port: 8082

message: "Hello World!"

myawesomefeature:
  flag: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3671/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true
